export const FETCH_BLOGS_START = 'FETCH_BLOGS_START';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE';
export const FETCH_BLOGS_END = 'FETCH_BLOGS_END';
