export const FETCH_PLACES_START = 'FETCH_PLACES_START';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE';
export const FETCH_PLACES_END = 'FETCH_PLACES_END';
