export const FETCH_PROPERTIES_START = 'FETCH_PROPERTIES_START';
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_FAILURE = 'FETCH_PROPERTIES_FAILURE';
export const FETCH_PROPERTIES_END = 'FETCH_PROPERTIES_END';

export const SEARCH_PROPERTIES_START = 'SEARCH_PROPERTIES_START';
export const SEARCH_PROPERTIES_SUCCESS = 'SEARCH_PROPERTIES_SUCCESS';
export const SEARCH_PROPERTIES_FAILURE = 'SEARCH_PROPERTIES_FAILURE';
export const SEARCH_PROPERTIES_END = 'SEARCH_PROPERTIES_END';
